### ISSUE TITLE
separate Showdown and MathJax processing properly

### ISSUE THREAD

**Issue by pkra** [fbreuer/qute-html5#40] opened 2011-08-18 23:54 UTC
One of the big conflicts I continuously see between markdown and mathjax are backslashes. LaTeX needs them, markdown considers them escape characters. So when I write something like ${ x : x< 0 }$, it will be rendered like $x: x<0$ would be.

Usually, I use backticks to force markdown to ignore TeX code. But for some reason this stopped working in Qute (although I don't know for sure if it worked with earlier versions). So now enclosing math in backticks prevents mathjax rendering.

What can we do about it? Is it just that mathjax adheres to skipping `<code>`? (I know you used to do that in your site's mathjax, but I can't see it in Qute's files)

Can we teach markdown to consider $ to be an escape character? (won't solve anything, I think)

**Comment by fbreuer** [comment] 2011-08-24 03:42
After writing some lecture notes with Qute, I experienced these issues myself.

1) Temporary workarounds. Wrapping TeX code in &lt;div>...&lt;/div> helps. Unfortunately, wrapping TeX code in &lt;span>&lt;/span> does not help. So I can only offer a workaround for display-level TeX code.

2) In the medium term we should definitely separate the MathJax and Showdown processors properly. One approach might be the following:
- before processing markdown: wrap all $...$ in &lt;div> tags with a special class. E.g. &lt;div class="tex">$...$&lt;/div>.
- process markdown: TeX code is ignored as it is wrapped in html tags.
- after processing markdown: remove &lt;div> tags again
- process mathjax: TeX code should be handled properly now.

3) I noticed that other Markdown processors can't handle TeX either, e.g., the one used in Jekyll. Have you had similar trouble with WordPress?

In general, these processing issues are going to appear in all systems that process Markdown but are not TeX aware. So even if Qute does everything correctly, the problems will still show up further down the publishing pipeline. The only solution I see right now, is to expand the export options of Qute, so that Qute can produce output that the rest of the publishing pipeline understands and that handles math gracefully. 

4) In the long run, I think the processing engine of Qute should be reimplemented. Or we should find a way to integrate PanDoc. Either choice means a _lot_ of work.

**Comment by fbreuer** [comment] 2011-08-24 03:53
BTW, this is mostly a duplicate of issue #17

**Comment by fbreuer** [comment] 2011-09-28 04:32
pkra mentioned that first applying MathJax and then applying Showdown should solve the issue.

I will try this for 0.4. If it does not work, then this is deferred until after the 0.5 rewrite.

**Comment by fbreuer** [comment] 2011-09-28 04:32
this is a duplicated of #17. will close #17 in favor of this one, as this one has more discussion.

**Comment by fbreuer** [comment] 2011-09-28 04:34
WORKAROUND:

The best way to workaround issues with { and } is to _escape the backslashes inside MathJax_. I.e. write \{ and \}!

**Comment by pkra** [comment] 2011-09-28 16:03
Did you mean `//}` etc?

**Comment by pkra** [comment] 2011-09-28 16:05
That works, but it's really bad because other systems (like pandoc and the markdown plugin for wordpress -- my scenario) do it properly and then you have to search and replace everything later...

**Comment by fbreuer** [comment] 2011-09-30 04:44
Great! The idea of first running MathJax and the Showdown, appears to solve most problems! 

Because of MathJax' asynchronous architecture, the code is a bit more convoluted than before and I believe transformation feels less responsive now, but the output is far more "correct" so this is an improvement!

@pkra: When did you get this idea of reversing the order of transformation?

**Closed as completed by fbreuer** 2011-09-30 04:44 UTC

**Comment by pkra** [comment] 2011-09-30 16:26
Well, I guess writing more led me to understand better how markdown works
(I'm lazy, I never really worked to understand it). Simply put, after
mathjax is done, you have some html code in your markdown which markdown
ignores.

The other way should work as well in the sense that you should at least get
consistent bugs. Right now, I find it most annoying that sometimes
subscripts get caught by markdown, sometimes by mathjax, all depending on
the actual content (e.g., if there's a < in the subscript which markdown
might or might not treat like an html tag depending on if you leave a space
before and after).

A different problem that we should think about in the long run: can we
extend markdown? Pandoc has a few nice extensions.

**Comment by fbreuer** [comment] 2011-10-01 01:13
regarding extensions: I just opened issue #47

**Comment by fbreuer** [comment] 2011-10-07 03:31
The approach of running MathJax and then Showdown also has its problems. For example Showdown escapes "<" -> "&lt;" inside mathml. This becomes a problem as soon as MathJax is run _again_ on the document - which happens for example after exporting the document to an HTML file.

I will open a separate issue on this.
