### ISSUE TITLE
double enter leaves editing mode

### ISSUE THREAD

**Issue by pkra** [fbreuer/qute-html5#35] opened 2011-07-16 13:49 UTC
If I hit enter fast twice, qute drops out of editing mode and I have to click back into a line to edit again.

Needless to say that sucks ;)

**Comment by fbreuer** [comment] 2011-07-16 14:35
hm, I cannot reproduce that. what I see is the following:

enter creates a new paragraph in edit mode. but this paragraph does not have keyboard focus (which should be fixed asap)

ctrl+enter creates a new paragraph in edit mode with keyboard focus. and no matter how fast I hit ctrl+enter again, I never drop out of edit mode.

**Comment by fbreuer** [comment] 2011-08-24 03:55
I think these are fixed now...?

**Closed as completed by fbreuer** 2011-08-24 03:55 UTC
